# Generated by Django 5.1.4 on 2025-01-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='category',
            field=models.CharField(choices=[('zakwaterowanie', 'Zakwaterowanie'), ('transport', 'Transport'), ('jedzenie', 'Jedzenie'), ('rozrywka', 'Rozrywka'), ('inne', 'Inne')], max_length=40),
        ),
    ]
