# Generated by Django 5.1.4 on 2024-12-31 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('user_id', models.IntegerField()),
                ('travel_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('main_destination', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField(verbose_name='Beginning of travel date')),
                ('end_date', models.DateTimeField(verbose_name='End of travel date')),
            ],
        ),
        migrations.CreateModel(
            name='Travel_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('travel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travplans.travel')),
            ],
        ),
    ]
